version: "3"
services:
  ecommerce-service:
    image: ecommerce-service
    ports:
      -"8080:8080"
    networks:
      - ecommerce-mysql
    depends_on:
      - docker-ecommerce

  docker-ecommerce:
    image: mysql:latest
    ports:
      - "3307:3306"
    networks:
      - ecommerce-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=ecommerce

  networks:
    ecommerce-mysql: